# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

variables:
  isMaster: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]

trigger:
  branches:
    include:
      - master

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: node_10
    displayName: Node 10
    jobs:
      - job: Install
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "10.x"
            displayName: "Install Node.js"

          - script: |
              npm install
              npm run build --if-present
              npm test
            displayName: "npm install, build, and test"

  - stage: publish
    displayName: Pack and Publish
    condition: and(succeeded(), eq(variables.isMain, true))
    jobs:
      - job: Pack
        steps:
          - script: |
              npm pack
            displayName: "Package for npm release"

          - task: CopyFiles@2
            inputs:
              SourceFolder: "$(Build.SourcesDirectory)"
              Contents: "*.tgz"
              TargetFolder: "$(Build.ArtifactStagingDirectory)/npm"
            displayName: "Copy npm package"

          - task: PublishBuildArtifacts@1
            condition: and(succeeded(), eq(variables.isMaster, true))
            inputs:
              PathtoPublish: "$(Build.ArtifactStagingDirectory)/npm"
              ArtifactName: npm
            displayName: "Publish npm artifact"
