# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

variables:
  isMaster: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]

trigger:
  branches:
    include:
      - master

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: install_build_test
    displayName: Install, build & test
    jobs:
      - job: node_16
        displayName: Node 16
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "16.x"
            displayName: "Install Node.js"

          - script: npm install
            workingDirectory: "example"
            displayName: "npm install (example)"

          - script: |
              npm install
              npm test
            displayName: "npm install & test"

      - job: node_18
        displayName: Node 18
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "18.x"
            displayName: "Install Node.js"

          - script: npm install
            workingDirectory: "example"
            displayName: "npm install (example)"

          - script: |
              npm install
              npm test
            displayName: "npm install & test"

      - job: node_20
        displayName: Node 20
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "20.x"
            displayName: "Install Node.js"

          - script: npm install
            workingDirectory: "example"
            displayName: "npm install (example)"

          - script: |
              npm install
              npm test
            displayName: "npm install & test"

  - stage: publish
    displayName: Pack and Publish
    condition: and(succeeded(), eq(variables.isMaster, true))
    jobs:
      - job: pack_and_publish
        displayName: Pack & Publish
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "16.x"
            displayName: "Node 16"

          - script: |
              npm pack
            displayName: "Package for npm release"

          - task: CopyFiles@2
            inputs:
              SourceFolder: "$(Build.SourcesDirectory)"
              Contents: "*.tgz"
              TargetFolder: "$(Build.ArtifactStagingDirectory)/npm"
            displayName: "Copy npm package"

          - task: PublishBuildArtifacts@1
            condition: and(succeeded(), eq(variables.isMaster, true))
            inputs:
              PathtoPublish: "$(Build.ArtifactStagingDirectory)/npm"
              ArtifactName: npm
            displayName: "Publish npm artifact"
